version: '3.4'

services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/debug
    entrypoint: sh -c "npx prisma db push && npx prisma generate && node prisma/seed.mjs && node dist/main"
    ports:
      - 3000:3000

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: debug
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.103.0.1/16
